### ISSUE TITLE
Results of enrichment with involved genes/miRNAs

### ISSUE THREAD

**Issue by loganylchen** [diwis/BUFET#1]
Hi there,

I was using BUFET to enrich my DE miRNAs, but found there were no involved genes or miRNAs in the results. Could you help me with that?

Best,

**Comment by diwis** [comment]
Hello. The output of BUFET was designed specifically to be the same as empiricalGO. The information provided is the name of the GO category, the number of genes in the GO category, the GO term overlap of the sample of interest, the mean overlap of the random miRNA groups with the GO category, the p-value and the Benjamini-Hochberg FDR indicator. 
Could you perhaps explain what you mean by "involved genes or miRNAs" so that I can understand and help you? Thanks!

**Comment by loganylchen** [comment]
Hi @diwis ,

Thanks for your reply. 
I meant genes or miRNAs that were involved( or enriched) in this GO term. For example, I used 10 miRNAs , and numbers of interactions between miRNA and their targets as input. The output was with only one GO term, providing P value, the number of overlap genes, etc. But I did not know the exact gene names of these overlap genes, or even the miRNA names targeting these genes. 

I hope I have made my question clearly. 

Best,

**Comment by diwis** [comment]
May I ask what kind of ontology and interaction files you are using? Are you using the form produced by miRanda and Enselmbl or are you using the alternative form?

**Comment by loganylchen** [comment]
I was using alternative form. 

For interaction:
```
output_mature_100|acanb
output_mature_100|adcy8
output_mature_100|aldob
output_mature_100|ap1s3b
```

For ontology:
```
a1cf|GO:0003676|nucleic acid binding
a1cf|GO:0003723|RNA binding
a1cf|GO:0003727|single-stranded RNA binding
a1cf|GO:0016556|mRNA modification
```

**Comment by diwis** [comment]
Okay then. I will create an extra python script that does exactly what you are asking. Keep in mind though, that the output will be very large.

**Comment by loganylchen** [comment]
@diwis Thanks.

**Comment by diwis** [comment]
Hello again, please take a look at section 3.5 in the README.md file.

**Comment by loganylchen** [comment]
@diwis Thanks for your help.
